### ISSUE TITLE
공통 컴포넌트 구현(서윤)

### ISSUE THREAD

**Issue by yunn23** [jnu-sf-engineering/frontend#9]
# 📌 작업 내용

- 화면에 사용될 공통 컴포넌트를 구현합니다.
  - 회고록 리스트 (RetroList)
  - 마크다운 에디터 (MarkdownEditor)
  - 마크다운 뷰어 (MarkdownViewer)
  - 프로젝트 리스트 (ProjectList)
  - 프로젝트 생성 모달 (ProjectCreateModal)
  - 네비바 (NavBar)
  <img width="955" alt="image" src="https://github.com/user-attachments/assets/8b17839d-b2a0-4563-9c83-c6ab75974434">

# 💡 참고사항

- @Klomachenko 공통 컴포넌트를 분리하려고 생각해봤는데, markdown 에디터를 사용하게 되면서 회고록 작성, 보기 화면에서는 딱히 생성할 컴포넌트가 없는 것 같습니다. 규민님이 생각하시기에 나올만한 공통 컴포넌트가 또 있을까요?

**Comment by Klomachenko** [comment]
markdown 에디터도 fix 되면 컴포넌트화 하셔야 할거에요!
